Convert floatPrecision to number instead of string
This seems to be accidentally removed here: https://github.com/jakearchibald/svgomg/commit/c5da12c59a810b05e94f80193251d73d1c66040d

Without it I see the following error when attempting to compress an svg file:

```
main-controller.js:268 Error: Minifying error: toFixed() digits argument must be between 0 and 20
```